FROM sonatype/nexus3:3.15.2

# LABEL nexus.interware.mx.version="3.15.2"
# LABEL nexus.interware.mx.tag="interware/nexus3:3.15.2"

# LABEL creator "Gerardo Cortés <gcortes@interware.com.mx>"
# LABEL maintainer "Gerardo Cortés <gcortes@interware.com.mx>"
