FROM gitlab/gitlab-ce:11.9.0-ce.0

# LABEL gitlab.interware.mx.version="11.9.0"
# LABEL gitlab.interware.mx.tag="interware/gitlab:11.9.0"

# LABEL creator "Gerardo Cortés <gcortes@interware.com.mx>"
# LABEL maintainer "Gerardo Cortés <gcortes@interware.com.mx>"
