FROM sonarqube:7.7-community

# LABEL nexus.interware.mx.version="7.7"
# LABEL nexus.interware.mx.tag="interware/sonarqube:7.7"

# LABEL creator "Gerardo Cortés <gcortes@interware.com.mx>"
# LABEL maintainer "Gerardo Cortés <gcortes@interware.com.mx>"
